updated files for stepper location
WebUI-Project-Based-07-vk/Client pull request #122
Opened 2024-08-11 18:45 UTC by SachkovaYuliia

![Screenshot_1](https://github.com/user-attachments/assets/c98d8a22-3317-46b3-873f-80163d90fc9a)
![Screenshot_2](https://github.com/user-attachments/assets/7e7b5a13-761c-4db3-82e9-fa7a2094615d)
This code should be checked at the same time as backend code #92.
Before testing, please make sure that your .env contains VITE_API_BASE_PATH.

2024-08-12 11:06 UTC, tufned requested changes

2024-08-12 11:06 UTC, tufned commented on src/containers/tutor-home-page/general-info-step/GeneralInfoStep.tsx
> +    fetchCountries().catch((error) => {
we don't need `fetchCountries().catch()`, because we already have one on line 60. 
Also if you want to do async operations inside useEffect, consider using this (without any addintional functions):
```
axios.get<CountryType[]>(`${basePath}/api/location/countries`)
  .then((response) => {
    ...
  })
  .catch((err) => {})
```

2024-08-12 11:06 UTC, tufned commented on src/containers/tutor-home-page/general-info-step/GeneralInfoStep.tsx
> +          console.log('Cities fetched:', response.data.cities)
Please remove `console.log` before merging

2024-08-12 11:06 UTC, tufned commented on src/containers/tutor-home-page/general-info-step/GeneralInfoStep.tsx
> +        try {
you have `try {} catch {}` inside another `try {} catch {}`

Please remove one of them, as we need only one

2024-08-12 11:06 UTC, tufned commented on src/containers/tutor-home-page/general-info-step/GeneralInfoStep.tsx
> +    handleCountryChangeAsync(e, newVal).catch((error) => {
again we don't need this `.catch()` here, because we are already handling errors catching inside `handleCountryChangeAsync()`

And overall consider removing `handleCountryChangeAsync()`, move it's content to `handleCountryChange()`, and just make `handleCountryChange()` an async function

something like this: 
```
const handleCountryChange = async (
    _e: React.SyntheticEvent,
    newVal: CountryType | null
  ) => {
    try {
      if (newVal && newVal.iso2) {
        const response = await axios.get<{
          label: string
          cities: CityType[]
        }>(`${basePath}/api/location/countries/${newVal.iso2}/cities`, {
          params: { countryName: newVal.label }
        })
        setCities(response.data.cities)
      } else {
        setCities([])
      }
      handleNonInputValueChange('country', newVal)
      resetData(['city'])
    } catch (error) {
      console.error('Failed to fetch cities:', error)
    }
  }
```
(instead of handleCountryChangeAsync() and handleCountryChange())

2024-08-12 11:06 UTC, tufned commented on src/containers/tutor-home-page/general-info-step/GeneralInfoStep.tsx
> +  useEffect(() => {
we also should add the request to get cities in this useEffect (on component mount) 
like this: 
```
 if (stepData !== stepDataInitialValues && stepData.country) {
  const response = await axios.get<{
    label: string
    cities: CityType[]
  }>(`${basePath}/api/location/countries/${stepData.country.iso2}/cities`, {
    params: { countryName: stepData.country.label }
  })
  setCities(response.data.cities)
}
```

to be able to render cities in this scenario:
- the country were selected and the city is not, 
- then we move to another step (so general info step component gets unmounted)
- we go back and want to select a city (but right now we don't have any options in this case)

2024-08-13 16:38 UTC, HalynaProlubshchykova approved these changes

2024-08-13 17:53 UTC, olehpona approved these changes

2024-08-15 08:22 UTC, vlad-khrychov approved these changes
Delete `console.log`-s and merge PR, thank you

2024-08-15 08:45 UTC, tufned approved these changes

2024-08-15 08:52 UTC, merged