Test/63/tests for user steps wrapper component
WebUI-Project-Based-07-vk/Client pull request #86
Opened 2024-07-23 08:42 UTC by HalynaProlubshchykova

Run the test using 'npm test tests/unit/components/user-steps-wrapper/UserStepsWrapper.spec.jsx\'

2024-07-23 10:25 UTC, olehpona approved these changes

2024-07-24 07:54 UTC, grbvtsk approved these changes

2024-07-25 13:40 UTC, MrAK-dev approved these changes

2024-07-25 13:41 UTC, MrAK-dev approved these changes

2024-07-26 10:30 UTC, vlad-khrychov requested changes
I`ve written to the [discord](https://discord.com/channels/1252591721641021440/1252597828941905940/1266340456053084233) chat about this PR.

2024-08-01 20:02 UTC, vlad-khrychov approved these changes

2024-08-01 20:05 UTC, merged