LanguageStep
WebUI-Project-Based-07-vk/Client pull request #91
Opened 2024-07-30 13:00 UTC by HalynaProlubshchykova

2024-07-30 13:32 UTC, grbvtsk approved these changes

2024-07-30 13:56 UTC, SeredenkoDS approved these changes
I'm not yet too experienced in React to leave a meaningful review sadly, but overall looks alright! Approving.

2024-07-30 14:27 UTC, olehpona approved these changes

2024-07-30 15:18 UTC, MrAK-dev approved these changes

2024-07-30 15:19 UTC, SachkovaYuliia approved these changes

2024-07-31 07:17 UTC, vlad-khrychov requested changes
Discuss with the team, maybe your styled components can be used for other steps as well.

2024-07-31 07:17 UTC, vlad-khrychov commented on src/containers/tutor-home-page/language-step/LanguageStep.jsx
> +          cooperate.
Use translation for all strings of front end

2024-07-31 07:17 UTC, vlad-khrychov commented on src/containers/tutor-home-page/language-step/LanguageStep.jsx
> +            <TextField {...params} label='Your native language' />
Use translation for all strings of front end

2024-07-31 07:17 UTC, vlad-khrychov commented on src/containers/tutor-home-page/language-step/LanguageStep.jsx
> +}))
I like the styled components approach, but move this code to another file to make the `LanguageStep.jsx` shorter.

2024-07-31 07:17 UTC, vlad-khrychov commented on src/containers/tutor-home-page/language-step/LanguageStep.jsx
> +}))
Do you think maybe this styled `Img` should be shared with other steps?

2024-07-31 18:50 UTC, vlad-khrychov requested changes
let`s rename the folder into `shared` and delete `.styles` from file names.

2024-08-01 02:35 UTC, vlad-khrychov approved these changes

2024-08-01 07:34 UTC, merged