Feature/83 84/add photo stepper
WebUI-Project-Based-07-vk/Client pull request #92
Opened 2024-07-30 18:53 UTC by olehpona

# How to test
## Start backend
```bash
npm run start
```
## Start client
```bash
npm run start
```
## Login to the tutor acount
![image](https://github.com/user-attachments/assets/6ed7f9bd-9a2a-4728-ab3f-c8ca30dc4413)
!!! Make sure that isFirstLogin equals true in db !!!
After that steper should open automaticly
## Chose photo page
![image](https://github.com/user-attachments/assets/3cf9faf5-55cc-4278-83c9-884502d727ea)
You should see this.

### Test cases
after pressing button should open file dialog
after selecting file that has type .png, .jpg, jpeg and has size less than 10 mb, image should be chosen and previewed
![image](https://github.com/user-attachments/assets/424b960b-5c37-4bd2-868f-85f5fcada003)
after presing button after choosing image, image should be removed and not previewed
after providing file with wrong type or size we should recieve alert with error and image should not be loaded
!!! This tast cases also should work when drag and drop file to photo preview area !!!
after drag file over preview area, area should get with solid border
![image](https://github.com/user-attachments/assets/e80b5ec7-00da-4b86-8375-88cd30280afd)

2024-07-30 19:10 UTC, HalynaProlubshchykova approved these changes

2024-07-30 20:05 UTC, SachkovaYuliia approved these changes

2024-07-31 06:04 UTC, grbvtsk approved these changes

2024-07-31 07:41 UTC, vlad-khrychov requested changes
Discuss with team that you have created `useStepContextType` and they should add `stepData` with fields and types that they need in their PR-s.

2024-07-31 07:41 UTC, vlad-khrychov commented on src/types/components/step-context/step-context.types.ts
> +  }
Have you used `stepData` in you code? If no just delete it for now, do not create `any` types.

2024-07-31 14:23 UTC, vlad-khrychov approved these changes

2024-07-31 14:24 UTC, merged