complete/task/55/test-content-switcher
WebUI-Project-Based-07-vk/Client pull request #93
Opened 2024-07-31 09:53 UTC by PavloChuchman

2024-07-31 10:24 UTC, SeredenkoDS approved these changes
Checked it out, the test runs and passes, and I think the code looks alright. Approving.

2024-07-31 11:31 UTC, HalynaProlubshchykova approved these changes

2024-07-31 13:50 UTC, grbvtsk approved these changes

2024-07-31 14:51 UTC, vlad-khrychov requested changes
Do not create a new component but test the existing one `src/components/app-content-switcher/AppContentSwitcher.tsx`

2024-08-15 12:29 UTC, vlad-khrychov approved these changes

2024-08-15 12:29 UTC, vlad-khrychov commented on src/components/app-range/AppRange.tsx
> +import React from 'react'
Do we actually need this import?

2024-08-15 12:29 UTC, vlad-khrychov commented on src/components/app-content-switcher/AppContentSwitcher.tsx
> +import React, { FC } from 'react'
Do we actually need this import?
```suggestion
import { FC } from 'react'
```

2024-08-16 07:35 UTC, merged